// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCypg1mRJ7EhvvmgnFsWXDVl6s3PSLoITU',
    appId: '1:766707208340:web:54f29c4a253cb977882481',
    messagingSenderId: '766707208340',
    projectId: 'crumbs-1ca81',
    authDomain: 'crumbs-1ca81.firebaseapp.com',
    databaseURL: 'https://crumbs-1ca81-default-rtdb.firebaseio.com',
    storageBucket: 'crumbs-1ca81.appspot.com',
    measurementId: 'G-KBY9RR0XR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCne56g6sf7aU4aVIGriUYg2icWaP3ciKs',
    appId: '1:766707208340:android:a22c56bce708bd63882481',
    messagingSenderId: '766707208340',
    projectId: 'crumbs-1ca81',
    databaseURL: 'https://crumbs-1ca81-default-rtdb.firebaseio.com',
    storageBucket: 'crumbs-1ca81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrXOdvgds6IVwtfhk9c-uR0hrr4k60SeY',
    appId: '1:766707208340:ios:2ac8d2ee230294f8882481',
    messagingSenderId: '766707208340',
    projectId: 'crumbs-1ca81',
    databaseURL: 'https://crumbs-1ca81-default-rtdb.firebaseio.com',
    storageBucket: 'crumbs-1ca81.appspot.com',
    androidClientId: '766707208340-c6gh9mp72jljnacsv7jpr3fpjovba6hk.apps.googleusercontent.com',
    iosClientId: '766707208340-3uci2r7qlaj5r1o7m6upgg3gtvcjd3ud.apps.googleusercontent.com',
    iosBundleId: 'com.example.crumbsFlutter1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrXOdvgds6IVwtfhk9c-uR0hrr4k60SeY',
    appId: '1:766707208340:ios:8f14fab1e5adc1e9882481',
    messagingSenderId: '766707208340',
    projectId: 'crumbs-1ca81',
    databaseURL: 'https://crumbs-1ca81-default-rtdb.firebaseio.com',
    storageBucket: 'crumbs-1ca81.appspot.com',
    androidClientId: '766707208340-c6gh9mp72jljnacsv7jpr3fpjovba6hk.apps.googleusercontent.com',
    iosClientId: '766707208340-7s2tm6eb50nv7a4g4bsfc14jjpct1skh.apps.googleusercontent.com',
    iosBundleId: 'com.example.crumbsFlutter1.RunnerTests',
  );
}
